### ISSUE TITLE
Suggestion: use `collapse::%!iin%` instead of `!%in%`

### ISSUE THREAD

**Issue by etiennebacher** [beniaminogreen/zoomerjoin#102]
Hello @beniaminogreen, the following lines take quite some time to run as the output becomes larger. 

https://github.com/beniaminogreen/zoomerjoin/blob/8392cd4f45fa6087203a66092c31eba268d93121/R/jaccard_join_core.R#L155-L156

I made a quick test with `collapse::%!iin%` instead of `!%in%` and found ~10% decrease in time and 15% decrease in memory used when both inputs have 300k rows:

```r
library(bench) 
library(dplyr)

out <- cross::run(
  pkgs = c("beniaminogreen/zoomerjoin", "etiennebacher/zoomerjoin@more-speedup"), 
  ~{
    library(zoomerjoin)
    
    ### Setup -----
    
    corpus_1 <- data.table::rbindlist(rep(list(dime_data), 300))
    names(corpus_1) <- c("a", "field")
    
    corpus_2 <- data.table::rbindlist(rep(list(dime_data), 300))
    names(corpus_2) <- c("b", "field")
    
    ### Benchmark -----
    
    bench::mark(
      jaccard_left_join(corpus_1, corpus_2, 
                        by = "field", n_gram_width=6,
                        n_bands=20, band_width=6, threshold = .8)
    )
  }
)

tidyr::unnest(out, result) |> 
  select(pkg, median, mem_alloc)
#> # A tibble: 2 × 3
#>   pkg                                     median mem_alloc
#>   <chr>                                 <bch:tm> <bch:byt>
#> 1 beniaminogreen/zoomerjoin                3.73m    18.5GB
#> 2 etiennebacher/zoomerjoin@more-speedup    3.28m    15.1GB
```
I don't know whether you'd be open to using `collapse` as a dependency (it only has `Rcpp` as dependency), but I think it'd be worth it as the performance gain should increase with the size of the data. Happy to make a PR if you're fine with that.

**Comment by beniaminogreen** [comment]
You are a machine! Happy to integrate this! I agree that it will make a big difference as the datasets get larger.  I frequently run zoomerjoin on datasets with ~300 million rows, where I imagine this change could save several minutes of runtime. 

Best, 
Ben
