### ISSUE TITLE
Error installing on Windows with Rust > 1.7.0

### ISSUE THREAD

**Issue by elaina-chen** [beniaminogreen/zoomerjoin#52]
Sorry for bothering. My system is Windows 11 and R version are 4.30 and 4.23. I used the two versions to install the package but both failed. For the RUST I used stable-x86-64-windows-msvc version 1.7.00 with toolchain gnu installed. The error message writes 

> undefined reference to `NtCreateFile'

 which could be the factor of error. Really appreciate for your help.

> E:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: ./rust/target/x86_64-pc-windows-gnu/release/libzoomerjoin.a(std-ca5208825e97b4ba.std.687851ba-cgu.0.rcgu.o): in function `std::sys::windows::fs::open_link_no_reparse':
> /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\sys\windows/fs.rs:800: undefined reference to `NtCreateFile'
> E:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\sys\windows/fs.rs:829: undefined reference to `RtlNtStatusToDosError'
> E:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: ./rust/target/x86_64-pc-windows-gnu/release/libzoomerjoin.a(std-ca5208825e97b4ba.std.687851ba-cgu.0.rcgu.o): in function `std::sys::windows::handle::Handle::synchronous_read':
> /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\sys\windows/handle.rs:241: undefined reference to `NtReadFile'
> E:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\sys\windows/handle.rs:272: undefined reference to `RtlNtStatusToDosError'
> E:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: ./rust/target/x86_64-pc-windows-gnu/release/libzoomerjoin.a(std-ca5208825e97b4ba.std.687851ba-cgu.0.rcgu.o): in function `std::sys::windows::handle::Handle::synchronous_write':
> /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\sys\windows/handle.rs:290: undefined reference to `NtWriteFile'
> E:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\sys\windows/handle.rs:318: undefined reference to `RtlNtStatusToDosError'
> collect2.exe: error: ld returned 1 exit status
> 無法產生 DLL 檔案 # Unable to produce DLL file
> ERROR: compilation failed for package 'zoomerjoin'
> * removing 'C:/Users/user/AppData/Local/Temp/RtmpW6qdAm/pkg-lib69c458dd7b3f/zoomerjoin'

**Comment by beniaminogreen** [comment]
Thanks for bringing this to my attention. Do you think you could try installing the package again using this command? 

```
devtools::install_github("beniaminogreen/zoomerjoin@windows_install") 
```

You are likely to see a lot of errors, but hopefully it will allow you to install the package on Windows using Rust > 1.7.  [this blog post](https://yutani.rbind.io/post/rust-1.70-and-build-failure-on-windows/) has an excellent rundown of the issues. I've opened a PR to fix this and if it works on your machine and doesn't cause any issues with the installation on Linux / MacOs I will merge it into the main branch.

**Comment by elaina-chen** [comment]
> Thanks for bringing this to my attention. Do you think you could try installing the package again using this command?
> 
> ```
> devtools::install_github("beniaminogreen/zoomerjoin@windows_install") 
> ```
> 
> You are likely to see a lot of errors, but hopefully it will allow you to install the package on Windows using Rust > 1.7. [this blog post](https://yutani.rbind.io/post/rust-1.70-and-build-failure-on-windows/) has an excellent rundown of the issues. I've opened a PR to fix this and if it works on your machine and doesn't cause any issues with the installation on Linux / MacOs I will merge it into the main branch.

No. It still shows the same error. Fortunately I just downloaded and installed Ubuntu 22 and all work fine. It may probably be caused by Rust running in Rtools windows cannot properly run windows command such as 'NtCreateFile'. I will try the solutions in the blog post and see if that can help run it on Windows.

BTW the package really helps me a lot in my research. Thank you very much!!!

**Comment by beniaminogreen** [comment]
Sorry I wasn't able to solve your issue, and thanks for the kind words about the package. I am merging the change in just because it helps on my server to install the package (even if it prints an insane amount of warnings while doing so)

**Comment by elaina-chen** [comment]
I tested 
`devtools::install_github("beniaminogreen/zoomerjoin@windows_install") `
 again today and magically it worked. I don't make many adjustments to my PC these days but I think I might wrongly run the command before.

Really appreciate your package!

**Comment by beniaminogreen** [comment]
Happy I was able to help! For future readers of this thread: I've merged this change into the main branch of the repo so that code won't work anymore - the change should be automatically applied to people installing the package on windows.
