### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by JosiahParry** [beniaminogreen/zoomerjoin#92]
**Is your feature request related to a problem? Please describe.**

This package is a great example of using R and Rust together and serves to fill a performance gap in the R ecosystem. The R community would benefit greatly from the publication of the library on CRAN.

Have you considered publishing to CRAN?

**Comment by beniaminogreen** [comment]
Hi Josiah, 

Thanks for reaching out. I have considered publishing the package to CRAN, but from what I have read [on the CRAN website](https://cran.r-project.org/web/packages/using_rust.html) and [in this blog post](https://yutani.rbind.io/post/a-quick-note-about-how-to-bundle-rust/), the process seems very difficult for packages that use both R and Rust.  

There are a few things I need to get to before this, but I will consider trying to get this on CRAN in the next few months. Do you have any experience publishing Rust crates to CRAN or any resources you could share on the process?

**Comment by JosiahParry** [comment]
I am more than happy to help! I have an existing PR to `rextendr` that would make this process a bit simpler. I have published two R packages to CRAN that utilize extendr and would be happy to help you in the submission process! :)

**Comment by beniaminogreen** [comment]
I am super busy over the next two weeks, but I will definitely take you up on that offer!

**Comment by beniaminogreen** [comment]
Back from my holidays and ready to make an effort on this front. I've found your branch of `rextendr` invaluable in preparing the package for CRAN submission - thanks so much for making it! I don't think it would have been possible for me to prepare the package without the helper functions you wrote. 

A quick question for you - this is basically the last `NOTE` I have to handle before a CRAN submission. Have you ever seen this before / have any leads for what to do to resolve it? I'm pretty mystified by it and did a search and can't find any of those flags in the package sources using grep. 

![image](https://github.com/beniaminogreen/zoomerjoin/assets/50080644/41344929-ada7-4710-9049-6c01ae1eae1b)


Best, 
Ben

**Comment by beniaminogreen** [comment]
I think I've managed to resolve this - looks like this was something that was specific to my Arch Linux machine. The only remaining NOTE I have before I am done with the submissions process is this one on the cran win-builder. Is this something to be expected when using rextendr, or should I do some digging to try and resolve this? 
![image](https://github.com/beniaminogreen/zoomerjoin/assets/50080644/b570f82b-890f-40b1-97ab-563a4810ee22)


Best, 
Ben

**Comment by beniaminogreen** [comment]
Fixed this and submitted to CRAN. Turned out to just be an issue with using an older version of the `extendr-api` crate.

**Comment by JosiahParry** [comment]
Well! Good for you! I was just about to comment saying I'll give this a clone and once over this evening. 🤞🏼

**Comment by beniaminogreen** [comment]
Excited to be able to share that the package has been accepted to CRAN and should be installable shortly.  Thanks for your help @JosiahParry, and closing the issue now!
